language: c
sudo: required
os:
  - linux
  - osx
env:
  global:
    - PACKAGE=interval
    - PINS="interval.dev:. interval_base.dev:. interval_intel.dev:. interval_crlibm.dev:."
  matrix:
    - OCAML_VERSION=4.11
    - OCAML_VERSION=4.10
    - OCAML_VERSION=4.09
    - OCAML_VERSION=4.08

install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh

notifications:
  email:
    - Christophe.Troestler@umons.ac.be
